# Generated by Django 4.0.3 on 2022-05-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0003_seller_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='apartment_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='renting.seller_profiles'),
        ),
    ]
