# Generated by Django 4.0.3 on 2022-05-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0004_houses_apartment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='apartment_img5',
            field=models.ImageField(blank=True, null=True, upload_to='images/apartments/'),
        ),
        migrations.AddField(
            model_name='seller_profiles',
            name='seller',
            field=models.BooleanField(default=False),
        ),
    ]
